# Generated by Django 3.0.2 on 2020-01-30 11:18

from django.db import migrations, models
import movies.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=movies.utils.movie_image_path)),
                ('trailer_url', models.URLField()),
            ],
        ),
    ]
